layout: { zmk_keyboard: corne }
layers:
  Base:
    - [TAB, Q, W, E, R, T, Y, U, I, O, P, BSPC]
    - [{ t: LCTRL, h: sticky }, A, S, D, F, G, H, J, K, L, ;, "'"]
    - [{ t: LSHFT, h: sticky }, Z, X, C, V, B, N, M, ",", ., /, "["]
    - [{ t: LGUI, h: sticky }, { t: Lower, h: Lower }, SPACE]
    - [RET, { t: Raise, h: sticky }, { t: LALT, h: sticky }]
  Lower:
    - [
        TAB,
        HOME,
        UP,
        PAGE UP,
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        "1",
        "2",
        "3",
        "-",
        "=",
        BSPC,
      ]
    - [
        { t: LCTRL, h: sticky },
        LEFT,
        DOWN,
        RIGHT,
        { t: ▽, type: trans },
        CLCK,
        "4",
        "5",
        "6",
        _,
        +,
        INSERT,
      ]
    - [
        { t: LSHFT, h: sticky },
        END,
        DOWN,
        PAGE DOWN,
        { t: ▽, type: trans },
        SLCK,
        "7",
        "8",
        "9",
        "0",
        DELETE,
        ESC,
      ]
    - [{ t: LGUI, h: sticky }, { type: held }, SPACE]
    - [RET, { t: ▽, type: trans }, { t: LALT, h: sticky }]
  Raise:
    - [TAB, "!", "@", "#", $, "%", ^, "&", KP MULTIPLY, (, ), BSPC]
    - [
        { t: LCTRL, h: sticky },
        AltGr+1,
        AltGr+2,
        AltGr+`,
        AltGr+4,
        { t: ▽, type: trans },
        AltGr+;,
        "`",
        "~",
        "AltGr+[",
        "AltGr+]",
        "]",
      ]
    - [
        { t: LSHFT, h: sticky },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        \,
        "|",
        AltGr+',
        AltGr+\,
        "}",
      ]
    - [{ t: LGUI, h: sticky }, { t: ▽, type: trans }, SPACE]
    - [RET, { type: held }, { t: LALT, h: sticky }]
  Function:
    - [F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12]
    - [
        { t: LCTRL, h: sticky },
        { t: BT, h: "0" },
        { t: BT, h: "1" },
        { t: BT, h: "2" },
        { t: BT, h: "3" },
        { t: BT, h: "4" },
        LEFT,
        DOWN,
        UP,
        RIGHT,
        { t: ▽, type: trans },
        BT CLR,
      ]
    - [
        { t: LSHFT, h: sticky },
        { t: Game, h: toggle },
        { t: Base, h: toggle },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
      ]
    - [{ t: LGUI, h: sticky }, { type: held }, SPACE]
    - [RET, { type: held }, { t: LALT, h: sticky }]
  Game:
    - [
        TAB,
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
      ]
    - [
        LCTRL,
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
      ]
    - [
        LSHFT,
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        ESC,
      ]
    - [LGUI, { t: ▽, type: trans }, SPACE]
    - [RET, { t: ▽, type: trans }, LALT]
