layout: { zmk_keyboard: corne }
layers:
  Base:
    - [TAB, Q, W, E, R, T, Y, U, I, O, P, BSPC]
    - [LCTRL, A, S, D, F, G, H, J, K, L, ;, "'"]
    - [LSHFT, Z, X, C, V, B, N, M, ",", ., /, "["]
    - [LGUI, { t: Lower, h: Lower }, SPACE]
    - [RET, { t: Raise, h: Raise }, RALT]
  Lower:
    - [
        TAB,
        { t: ▽, type: trans },
        UP,
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        "7",
        "8",
        "9",
        HOME,
        END,
        BSPC,
      ]
    - [
        LCTRL,
        LEFT,
        DOWN,
        RIGHT,
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        "4",
        "5",
        "6",
        PAGE UP,
        PAGE DOWN,
        INSERT,
      ]
    - [
        LSHFT,
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        "1",
        "2",
        "3",
        "0",
        DELETE,
        ESC,
      ]
    - [LGUI, { type: held }, SPACE]
    - [RET, { t: ▽, type: trans }, RALT]
  Raise:
    - [TAB, "!", "@", "#", $, "%", ^, "&", KP MULTIPLY, (, ), BSPC]
    - [
        LCTRL,
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        "-",
        "=",
        "[",
        "]",
        \,
        "`",
      ]
    - [
        LSHFT,
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        _,
        +,
        "{",
        "}",
        "|",
        "~",
      ]
    - [LGUI, { t: ▽, type: trans }, SPACE]
    - [RET, { type: held }, RALT]
  Function:
    - [F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12]
    - [
        LCTRL,
        { t: BT, h: "0" },
        { t: BT, h: "1" },
        { t: BT, h: "2" },
        { t: BT, h: "3" },
        { t: BT, h: "4" },
        LEFT,
        DOWN,
        UP,
        RIGHT,
        { t: ▽, type: trans },
        BT CLR,
      ]
    - [
        LSHFT,
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
        { t: ▽, type: trans },
      ]
    - [LGUI, { type: held }, SPACE]
    - [RET, { type: held }, RALT]
